### PR TITLE
Support ubuntu/debian

### PR DESCRIPTION
**Pull request by redterror**
Everything pretty much works.

### CODE REVIEW

**Comment by rchukh** [comment]
Thanks.

I will try to take a look into it in the next few days (add some unit tests for ubuntu, update default kibana version to 4.0.0-BETA2, etc.).

Regarding the pessimistic dependencies - the ES dependency, for example, is still less than 1.0, so it may have some significant changes in 0.4/.../0.X versions, that is why I would like to keep it to ">= 0.3.10" and "< 0.4".

**Comment by redterror** [comment]
Were you able to get them to resolve recently?  I wasn't able to complete a `berks install` with the way they are specified upstream.

**Comment by rchukh** [comment]
Java dependency - I am going to remove the patch version for it (as in this pull-request).

As for ElasticSearch...

The reason that it is not updating to 0.3.11 right now is that chef supermarket does not know about 0.3.11... the latest is 0.3.10 - https://supermarket.chef.io/cookbooks/elasticsearch
There is even a issue related to it: https://github.com/elasticsearch/cookbook-elasticsearch/issues/250

As for now - I will probably change the dependency to point to github.

**Comment by rhass-r7** [comment]
:+1: I am happy to see both this cookbook and this patch. @redterror You may want to also add ubuntu and/or debian to the platforms in .kitchen.yml before this patch gets landed.

**Comment by rhass-r7** [comment]
In addition to my previous suggestion, you may want to consider the follow patch:

``` diff
diff --git a/metadata.rb b/metadata.rb
index 0d04698..4728b41 100644
--- a/metadata.rb
+++ b/metadata.rb
@@ -23,7 +23,8 @@ EOH
 depends 'chef-sugar', '~> 2.4'
 depends 'line', '~> 0.5'
 depends 'ark', '~> 0.9'
 depends 'java', '~> 1.28'
+depends 'apt', '~> 2.6.0'

 # Optional dependencies
 # FIX: 'depends' because of https://github.com/acrmp/foodcritic/issues/159
diff --git a/recipes/dependencies.rb b/recipes/dependencies.rb
index 37ac2b7..3e85dd3 100644
--- a/recipes/dependencies.rb
+++ b/recipes/dependencies.rb
@@ -5,6 +5,7 @@
 include_recipe 'chef-sugar::default'

 if node['kibana']['dependency']['install_java']
+  if platform_family?('debian') then include_recipe 'apt::default' end
   include_recipe 'java::default'
 else
   ruby_block 'check_java' do
```

In my tests via test-kitchen, I was unable to converge the node when installing java due to the apt cache being stale. Technically, this is a bug in the java cookbook, but I will leave it here for the consideration of you both. Pull-Request submitted to @redterror with the provided patch.

**Comment by rchukh** [comment]
Thanks!

I will close this pull-request and create a separate from @redterror repo (to the ubuntu branch instead master branch).

After that I'll merge @rhass-r7 changes, and will do some tests before merging them into master.

**Comment by rchukh** [comment]
@redterror , @rhass-r7 
I have just released a 0.2.0 version with all those changes that were provided, and some additional fixes.

https://supermarket.chef.io/cookbooks/chamber-kibana/versions/0.2.0

**Comment by redterror** [comment]
Awesome, thanks!

**Pull request closed without merging**
